wm_base:

  Archlinux:
    services:
      - acpid
      - atd
      - cronie

    packages:
      - acpid
      - alacritty
      - at
      - blueman
      - bluez
      - broot
      - btop
      - cronie
      - easyeffects
      - expect
      - ffmpegthumbnailer
      - fzf
      - fzy
      - glances
      - grc
      - grim
      - gsettings-desktop-schemas
      - gtop
      - gvfs
      - gvfs-smb
      - hexedit
      - highlight
      - icoutils
      - iftop
      - imagemagick
      - inotify-tools
      - iotop
      - kitty
      - libnotify
      - libqalculate
      - mpc
      - mpd
      - mpv
      - ncdu
      - ncmpcpp
      - network-manager-applet
      - networkmanager-openvpn
      - newsboat
      - nmap
      - nwg-look
      - pamixer
      - pass
      - pavucontrol
      - pdftk
      - perl-file-mimeinfo
      - pipewire
      - pipewire-pulse
      - playerctl
      - pulsemixer
      - python
      - python-pip
      - qt5-wayland
      - qt5ct
      - qt6-wayland
      - qt6ct
      - shellcheck
      - slurp
      - smbnetfs
      - sshfs
      - syncthing
      - tk
      - tmux
      - trash-cli
      - tree
      - udiskie
      - udisks2
      - v4l-utils
      - vbindiff
      - vulscan
      - w3m
      - wireplumber
      - wmctrl
      - wmname
      - xcape
      - xdg-utils
      - yarn
      - yq
      - yt-dlp
      - zathura
      - zathura-pdf-mupdf
