apps:
  Archlinux:
    packages:
      - fcitx5 
      - fcitx5-bamboo 
      - fcitx5-configtool
      - fcitx5-gtk
      - fcitx5-mozc
      - fcitx5-qt 
      - firefox
      - flameshot
      - gimp
      - lazygit
      - mpv
      - obs-studio
      - stow
      - thunderbird
      - vivaldi
