wm_hyprland:

  Archlinux:
    packages:
      - hyprcursor
      - hypridle
      - hyprland
      - hyprlock
      - hyprpaper
      - hyprpolkitagent
      - uwsm
      - qt5-svg
      - qt5-wayland
      - qt5-graphicaleffects
      - qt5-quickcontrols2
      - qt6-wayland 
      - rofi-wayland
      - swaync
      - waybar
      - xdg-desktop-portal-hyprland
      - gnome-keyring

    conflicts:
      - dunst
      - mako
      - rofi
