base:
  Archlinux:
    services:
      - haveged
      - NetworkManager
      - rngd

    packages:
      - arch-audit
      - bash-completion
      - base-devel
      - bind-tools
      - bridge-utils
      - cifs-utils
      - clang
      - compiler-rt
      - cryfs
      - curl
      - devtools
      - diff-so-fancy
      - dosfstools
      - git
      - openbsd-netcat
      - gnupg
      - go
      - gzip
      - haveged
      - hdparm
      - i2c-tools
      - lm_sensors
      - man-db
      - man-pages
      - mkcert
      - mlocate
      - net-tools
      - networkmanager
      - nfs-utils
      - npm
      - ntfs-3g
      - nvme-cli
      - oath-toolkit
      - openssh
      - openvpn
      - p7zip
      - pkgfile
      - powertop
      - pv
      - pyenv
      - python-pip
      - python-virtualenv
      - python
      - rclone
      - reflector
      - rng-tools
      - rsync
      - rustup
      - sshfs
      - sudo
      - tar
      - tree
      - ufw
      - unzip
      - usb_modeswitch
      - usbutils
      - valgrind
      - vde2
      - wget
      - whois
      - wireguard-tools
      - wol
      - xdg-user-dirs
      - zip
