modern_unix:

  Archlinux:
    packages:
      - bat
      - git-delta
      - duf
      - fd
      - fzf
      - jq
      - ripgrep
      - tldr
      - zoxide

  Ubuntu:
    packages:
      - batcat
      - duf
      - fd
      - fzf
      - tldr
      - jq
      - ripgrep
      - zoxide
